### PR TITLE
Module type checking

### PR DESCRIPTION
**Pull request by 0joshuaolson1**
Fixes https://github.com/Picolab/pico-engine/issues/305 and https://github.com/Picolab/pico-engine/issues/272.

AppVeyor is having trouble running anything.

I didn't do much for app, engine, ent, event, or schedule. meta has no functions yet that need extra checking.

I decided not to use [parambulator](https://www.npmjs.com/package/parambulator) or [ajv](https://www.npmjs.com/package/ajv) - parambulator looks nicer for partial checking inline while computing other things, but what we're doing is simple anyway, and neither library seems to let me throw a custom semantically correct error like TypeError!

### CODE REVIEW

**Comment by 0joshuaolson1** [comment]
Thanks for readying this for merge!

**Comment by farskipper** [comment]
Overall looks good. I made two small commits.

#### send_directive(name, options)
Do we really want to make `name` optional? I think we should simply always require `name` and it must be a string. It'll keep things simpler, easier to document, less surprises etc.

#### testing error messages
Something to consider when testing error messages. There is a lot to gain by testing the entire error message string, rather than just the error type.

```js
var foo = function(bar){
    throw new TypeError(“some specific message about: ” + bar)
}

try{
    foo(“WAT”);
    t.fail(“should throw”);
}catch(e){
    t.equals(e + “”, “TypeError: some specific message about: WAT”);
}
```

The advantage is you know exactly which error was raised, and check that any context contained in the error message is correct (in this case “WAT”). Also it makes the tests read nicely since you know exactly what the error was and what you expected it to be.

The “disadvantage” is it takes a little more work since it's more verbose and changing an error message requires changing tests. I think it’s well worth cost, since it doesn't really take that long and you get better tests in the end.

**Comment by 0joshuaolson1** [comment]
I don't feel strongly about my approach. I'll make those two changes here.

**Comment by 0joshuaolson1** [comment]
Take 2

**Comment by farskipper** [comment]
Nice, looks good!

**Pull request merged**
