### PR TITLE
Add pico names on header and about page

### PR DESCRIPTION
**Pull request by nmartinezbyu**
I made a change where you can see the picos name in the header and the parent and children names in the about page. Also in this pull request is a change for the close button where it is not up against the corner anymore. I saw @KandareJ make the close button change to his engine and I copied it. This was done in order to give a better developer experience and for me to get a better understanding on how the new pico engine works. @b1conrad can you look over my changes and tell me what you think?

### CODE REVIEW

**Comment by b1conrad** [comment]
What do I have to do to get the new branch so that I can try it out? This is what I have done: 

```
git fetch origin
git checkout pico-framework-pico-names
npm run setup
npm start
```

but I don't see anything different

**Comment by nmartinezbyu** [comment]
My last commit should have fixed the issue with not seeing the changes.

**Comment by b1conrad** [comment]
I like it. Thank you, @nmartinezbyu

**Review by b1conrad — APPROVED** [review]
Looks good, no, great

**Pull request merged**
