### PR TITLE
Optimize stdlib sort

### PR DESCRIPTION
**Pull request by 0joshuaolson1**
Tiny iterative async merge sort (fixes https://github.com/Picolab/pico-engine/issues/298) - I should totes make this an npm module.

### CODE REVIEW

**Comment by farskipper** [comment]
Looks good, yeah a module for this would be nicer. I just found https://www.npmjs.com/package/async-merge-sort which is similar. Or make a async-quicksort based off of https://gist.github.com/greim/c0fff3eb8c48a2774aab

I'll leave it up to you if you want to invest more in this. If not I think this is fine to merge.

**Comment by 0joshuaolson1** [comment]
Cool. I like the current method. The async merge library has a lot of array creation churn, and if we're more worried about average performance than worst-case there are better non-quicksort-based libraries (but I can't decide which to use...).

**Comment by 0joshuaolson1** [comment]
I'll pull the sort logic out into a file for now.

**Comment by 0joshuaolson1** [comment]
Separated.

**Comment by 0joshuaolson1** [comment]
Dang it, I have to fix something.

**Comment by farskipper** [comment]
Is the the issue with odd number of items? i.e. `[5, 3, 4, 1, 12]` 12 is never compared

**Comment by 0joshuaolson1** [comment]
Yeah, I messed up something from the original algorithm.

**Comment by 0joshuaolson1** [comment]
I found out `grin` wasn't iterating the way merge sort should anyway. Let's try this.

**Comment by 0joshuaolson1** [comment]
Thanks again. I wasn't sure about the extent of tests we need.

**Comment by farskipper** [comment]
Oh np, I just added those to be sure I knew it was handling those cases.

**Pull request merged**
