### PR TITLE
Engine module type checks

### PR DESCRIPTION
**Pull request by 0joshuaolson1**
At some point during my engine.test.js modifications, one of the random module's random number functions kept failing with out-of-bounds values.

It went away, but I imagine such a spurious thing can come back one day.

### CODE REVIEW

**Comment by 0joshuaolson1** [comment]
There's a new lint or something against specifying a default JS argument. Easy fix, will do soon.

**Comment by farskipper** [comment]
The merge issue was mkKRLfn  argument order changed, and the way module actions are defined. So I went ahead and made that fix for you.

`assertPicoID` is breaking the callback conventions. The callback should always be the last parameter and you should use it for both error and success. (i.e. no `onOk` callback)
I know it may always having to check the callback error, but following callback rules keeps things sainer. I recommend reading: http://callbackhell.com/ for a longer explanation.

One idea. Just change the error messages in `DB.js` line 293 and 297. That way you can be more specific when type was wrong or that it was not found.

I like the idea of including the function name in the error message. Eventually we’ll need to trace errors to the krl source code that caused it taking advantage of our sourcemaps. But for now you can do something like this when intercepting error messages:
```js
if(_.isString(err.message)){
    err.message = "engine:newPico " + err.message;
}
```
This way it retains the error type i.e. NotFoundError and `err.notFound`

**Comment by 0joshuaolson1** [comment]
Whoops, I only meant to intercept the DB's _.isString. The general function-name-in-error/source map idea is a much bigger project.

I made assertPicoID use Node conventions (you caught me!), but note that this means
- duplicate error checking by the caller that could be done in the function, which is used in a specific, private case
- no optional `idDescription` parmeter (have to write `void 0` for most calls) - eslint currently complains about default arguments

**Comment by 0joshuaolson1** [comment]
> arguments.length

Oh yeah, forgot about that. That would've been more flexible.

**Comment by 0joshuaolson1** [comment]
Why hide `krl-stdlib/strictEquals`? I thought how `krl-stdlib/types` did it was a good idea.

**Comment by farskipper** [comment]
I exposed  `require("krl-stdlib/types")` because that is something I think should be part of it's supported API.

`strictEquals` on the other hand is just a utility for `tape` we are using internally and not related to krl, so I don't think it should be exposed like that. If you want I think you could submit a PR to `"tape"` adding `t.deepEqualsStrict` or publish a small module that monkey patches it or something.

**Pull request merged**
